[[ACCOUNTS]]
address = "rm2FabxuAxQWWmrYnTn1rQnmPmyLee4gB"
network = "testnet"
desc = "Issuer account for RLU"

[[CURRENCIES]]
code = "62524C5553440000000000000000000000000000"
issuer = "rm2FabxuAxQWWmrYnTn1rQnmPmyLee4gB"
network = "testnet"
display_decimals = 2
symbol = "$"
