[[ACCOUNTS]]
address = "rm2FabxuAxQWWmrYnTn1rQnmPmyLee4gB"
network = "main"
desc = "bRLUSD is a yield-accruing vault token."

[[CURRENCIES]]
code = "62524C5553440000000000000000000000000000"
issuer = "rm2FabxuAxQWWmrYnTn1rQnmPmyLee4gB"
network = "main"
display_decimals = 2
symbol = "$"
icon = ""https://xbotfi.github.io/assets/brlusd.png

[[ACCOUNTS]]
address = "rm2FabxuAxQWWmrYnTn1rQnmPmyLee4gB"
network = "testnet"
desc = "bRLUSD is a yield-accruing vault token."

[[CURRENCIES]]
code = "62524C5553440000000000000000000000000000"
issuer = "rm2FabxuAxQWWmrYnTn1rQnmPmyLee4gB"
network = "testnet"
display_decimals = 2
symbol = "$"
icon = ""https://xbotfi.github.io/assets/brlusd.png
